import { StyleSheet} from "react-native";
import Colors from "../../components/common/Colors";
const style=(width,height)=>StyleSheet.create({
    container:{ 
        flex:1,
        backgroundColor:Colors.flashwhite,
        padding:10,
        // paddingHorizontal:20
    },
    productview:{             
        width:'100%',
        padding:15,
        marginVertical:15,
        marginRight:15,
        borderRadius:15,
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:Colors.white,
        overflow:'hidden',
        },
    productimage:{
        width:75,
        height:75,
        resizeMode:'contain',
        alignSelf:'center',
        marginVertical:15,
    },
    innerview1:{ 
         borderLeftWidth:1,
        paddingHorizontal:10,
        marginLeft:10,
        width:width*.68
    },
    head1:{
        fontFamily:'Poppins-Bold',
        fontSize:20,
        color:Colors.black
    },
    priceview:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:15,
        width:width*.625

    },
    priceview2:{
        flexDirection:'row',
        alignItems:'center',
    },
    des:{
        fontFamily:'Poppin-Regular',
        fontSize:16,
        color:Colors.jetblack,

    },
    pricetext:{
        fontFamily:'Poppins-Bold',
        fontSize:18,
        color:Colors.black
    },
    offview:{
        backgroundColor:Colors.green,
        padding:4,
        borderRadius:20,
        marginHorizontal:15
        

    },
    offtext:{
        fontFamily:'Poppins-SemiBold',
        fontSize:16,
        color:Colors.white,
        marginHorizontal:10,

    },
    qunview:{
        justifyContent:'space-around',
        alignItems:'center',
        flexDirection:'row',
        borderRadius:20,
        borderWidth:1,
        borderColor:Colors.green,
        overflow:'hidden',
        paddingVertical:3,
    },
    quntext1:{
        fontFamily:'Poppins-Bold',
        fontSize:20,
        color:Colors.black,
        marginHorizontal:10,

    },
    quntext2:{
        fontFamily:'Poppins-Bold',
        fontSize:18,
        color:Colors.green,
        marginHorizontal:5,
    },
    outerview: {
        flexDirection:'row',
        alignItems:'center',
        width:width*.95,
        alignSelf:'center',
        justifyContent:'center',
        marginBottom:height*.005,
        marginTop:20
    },
    bview:{marginRight:height*-.025/2,zIndex:99},
    innerview:{
        width:25,
        height:25,
        borderRadius:25/2,
        backgroundColor:Colors.flashwhite,
    },
    leftview:{ 
        height:100,
        width:'65%',
        backgroundColor:Colors.secondayGreen,
        padding:20,
         },
         insideleft:{
            flexDirection:'row',
            alignItems:'center'
        },
        offertext:{
            fontFamily:'Poppins-Bold',
            color:Colors.green,
            fontSize:40
        },
        off:{
            fontFamily:'Poppins-Regular',
            color:Colors.green,
            fontSize:12
        },
        head:{
            fontFamily:'Poppins-Bold',
            color:Colors.black,
            fontSize:16
        },
        content:{
            fontFamily:'Poppins-Regular',
            color:Colors.black,
            fontSize:12
        },
        bg:{
            justifyContent:'space-between',
            height:100,
            backgroundColor:Colors.secondayGreen
          },
          sideview:{
            height:25,
            width:25,
            borderRadius:12.5,
           backgroundColor:Colors.flashwhite,
           marginTop:-25/2
          },
          sideview2:{
          height:25,
          width:25,
          borderRadius:12.5,
         backgroundColor:Colors.flashwhite,
         marginBottom:-25/2
          },

          right:{ height:100,width:'25%',
          backgroundColor:Colors.secondayGreen,
          paddingRight:15,
          paddingVertical:15,
          justifyContent:'center',
          alignItems:'center'
           },
           codehead:{
            fontFamily:'Poppins-Regular',
            color:Colors.black,
            fontSize:14
        },
        codeview:{
            marginVertical:10,
            paddingHorizontal:10,
            paddingVertical:5,
            justifyContent:'center',
            borderRadius:20,
            backgroundColor:Colors.green,
            overflow:'hidden',
        },
        codetext:{
            fontFamily:'Poppins-Regular',
            color:Colors.white,
            fontSize:12,
            textAlign:'center'
        }
    
    }
)
export default style;