import { StyleSheet } from "react-native";
import Colors from "../../components/common/Colors";
const style=(height,width,isPortrait)=>StyleSheet.create({
    scroll:{padding:width*.015,},
    view1:{
        backgroundColor:Colors.green,
        padding:width*.015,
        borderRadius:width*.017,
        justifyContent:'flex-start',
        flexDirection:'row',
        alignItems:'center',
        marginVertical:width*.015
        },
        contentContainerStyle:{paddingBottom:width*.15},
        idview:{marginLeft:width*.020},
        id:{
            fontFamily:'Poppins-Regular',
            fontSize:16,
            color:Colors.white
        },
        ordertext:{
            fontFamily:'Poppins-Black',
            fontSize:20,
            color:Colors.white
        },
        view2:{marginVertical:width*.015},
        head:{
            fontFamily:'Poppins-Bold',
            fontSize:20,
            color:Colors.green
        },
        outerview:{
            flexDirection:'row',
            alignItems:'center',
            marginVertical:5,
            justifyContent:'space-between'
        },
        innerview:{
            paddingHorizontal:width*.015,
            paddingVertical:width*.002,
            backgroundColor:Colors.green,
            borderRadius:10,
            margin:width*.015
        },
        quantity:{
            fontFamily:'Poppins-Bold',
            fontSize:18,
            color:Colors.white
        },
        itemview:{
            width:'50%',
            overflow:'hidden',
            marginLeft:10
        },
        name:{
            fontFamily:'Poppins-Bold',
            fontSize:16,
            color:Colors.black
        },
        desc:{
            fontFamily:'Poppins-Regular',
            fontSize:14,
            color:Colors.Gray
        },
        priceview:{width:'20%'},
        price:{
            fontFamily:'Poppins-Bold',
            fontSize:16,
            color:Colors.charcol
        },
        coupon:{
            fontFamily:'Poppins-Regular',
            fontSize:16,
            color:Colors.green,
            lineHeight:30
        },
        payment:{
            marginVertical:width*.015,
            justifyContent:'space-between',
            alignItems:'center',
            flexDirection:'row',
            borderBottomColor:Colors.Gray,
            borderBottomWidth:1,
            paddingBottom:20
        },
        text:{
            fontFamily:'Poppins-Regular',
            fontSize:16,
            color:Colors.black,
            lineHeight:30
        },
        totalview:{
            justifyContent:'space-between',
            alignItems:'center',
            flexDirection:'row'
        },
        total:{
            fontFamily:'Poppins-Bold',
            fontSize:18,
            color:Colors.black
        },
        address:{
            fontFamily:'Poppins-Regular',
            fontSize:16,
            color:Colors.Gray,
            lineHeight:23
        },
        iconview:{
            marginVertical:15,
            justifyContent:'flex-start',
            alignItems:'center',
            flexDirection:'row'
        },
        onlineview:{marginLeft:15 },
        online:{
            fontFamily:'Poppins-Regular',
            fontSize:16,
            color:Colors.black
        },
        button:{
            position:'absolute',
            bottom:0,
            padding:width*.015,
            width:'100%',
            backgroundColor:Colors.white
        },
})
export default style;