import { StyleSheet,Dimensions } from "react-native";
import Colors from "../../components/common/Colors";
const style=(width,height,isPortrait)=>StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:Colors.WhiteSmoke,
    },
    containerstyle:{
        paddingBottom:20
    },
    touch:{
        padding:15,
        borderRadius:15,
        overflow:'hidden',
        backgroundColor:Colors.LightGreen,
        marginTop:15,
        marginHorizontal:15
    },
    innerview:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        borderBottomColor:Colors.Gray,
        borderBottomWidth:1,
        paddingBottom:15
    },
    orderid:{
        fontFamily:'Poppins-Bold',
        fontSize:16,
        color:Colors.black
    },
    date:{
        fontFamily:'Poppins-Regular',
        fontSize:14,
        color:Colors.green
    },
    address:{
        fontFamily:'Poppins-Regular',
        fontSize:14,
        color:Colors.Gray
    },
    paid:{
        fontFamily:'Poppins-Regular',
        fontSize:14,
        color:Colors.black
    },
    price:{
        fontFamily:'Poppins-Regular',
        fontSize:16,
        color:Colors.green
    },
    image:{
        height:100,
        width:100,
        resizeMode:'cover',
        borderRadius:15,
        overflow:'hidden'
      },
      rateview:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingTop:15,
    },
    order:{
        fontFamily:'Poppins-Regular',
        fontSize:16,
        color:Colors.black
    },
    emptyview:{
        justifyContent:'center',
        alignItems:'center',
        padding:15
    },
    emptytext:{
        fontFamily:'Poppins-Bold',
        fontSize:20,
        color:Colors.Gray
    },
    shoptext:{
        fontFamily:'Poppins-Regular',
        fontSize:16,
        color:Colors.Gray
    },
    }
)
export default style;